name: Release NuGet Package

on:
  push:
    tags:
      - "vG2022073898" 

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Pack NuGet
      run: dotnet pack Bank.Domain/Bank.Domain.csproj -c Release -o out /p:PackageVersion=${GITHUB_REF##*/v}

    - name: Push NuGet to GitHub Packages
      run: dotnet nuget push "out/*.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: Publicación automática del paquete con versión del estudiante.
